# Generated by Django 4.1.3 on 2022-12-09 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('serving', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('ingredient', models.TextField(blank=True, null=True)),
                ('method', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.label')),
            ],
        ),
    ]
